### ISSUE TITLE
Highlighting is sometimes not removed when unmarking a portion of a block of previously marked lines

### ISSUE THREAD

**Issue by lemeizhang** [DeFacto-UW/DeMark#3]
For some lines, the bookmark goes away but the highlighting is still there.
It can be reproduced sometimes by marking multiple lines at once, and then unmarking some lines that are between the first marked lines and the last marked line.

**Comment by anhnamtran** [comment]
Referenced in #7. 
Closed after this [commit](https://github.com/DeFacto-UW/DeMark/commit/8c4dfc5e2eaee9b54be5a2027e65db0c2a76e4fd).
