### ISSUE TITLE
Cannot mark lines that contain only whitespace or closing curly bracket

### ISSUE THREAD

**Issue by lemeizhang** [DeFacto-UW/DeMark#4]
The line will not get bookmarked nor highlighted if it only contains whitespace or closing curly bracket "}".
Reproduce by marking multiple lines, where some of the lines only contain whitespace or closing curly bracket.

**Comment by anhnamtran** [comment]
Just wanted to note that this issue only happens in batch marking. Meaning that if you're marking the lines individually this issue does not happen.

**Comment by anhnamtran** [comment]
Closed by this [commit](https://github.com/DeFacto-UW/DeMark/commit/8c4dfc5e2eaee9b54be5a2027e65db0c2a76e4fd) after batch marking was fixed in #7.
